apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argo
  labels:
    app: minio
spec:
  project: default
  source:
    repoURL: https://gitlab.com/tomkukral/training-model.git
    targetRevision: HEAD
    path: minio
  destination:
    name: in-cluster
    namespace: minio
  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true
